server.port=8080
spring.application.name=ParcouComp
spring.thymeleaf.cache=false
server.error.include-exception=false
server.error.include-message=never

# API Football-Data.org
football.api.key=11363b42c2384dca874a83fe6d6e4c74
football.api.url=https://api.football-data.org/v4

# PostgreSQL Database (supprime toute référence à H2)
spring.datasource.url=jdbc:postgresql://localhost:5432/parcoucomp_db
spring.datasource.username=parcoucomp_user
spring.datasource.password=parcoucomp_mdp
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Désactiver complètement H2
spring.h2.console.enabled=false